version: "3.7"

networks:
  frontend:
  backend:

volumes:
  mariadb:
  include:
  filestore:

services:
  resourcespace:
    image: joppes/resourcespace:latest
    restart: unless-stopped
    depends_on:
      - mariadb
    volumes:
      - include:/var/www/html/include
      - filestore:/var/www/html/filestore
    networks:
      - frontend
      - backend
    ports:
      - 80:80

  mariadb:
    image: mariadb
    restart: unless-stopped
    env_file:
      - db.env
    volumes:
      - mariadb:/var/lib/mysql
    networks:
      - backend
